### ISSUE TITLE
会議室予約一覧の表示をスクロール対応にし、予約件数が多くなってもUIが崩れないようにする

### ISSUE THREAD

**Issue by t-yamagro** [t-yamagro/mtg-room-reserve#2]
## 概要
現在、会議室予約情報の一覧は全件をそのまま表示しているため、予約件数が多くなると画面が縦に大きく伸びてしまい、UIが崩れる・操作性が低下する問題があります。

## 再現手順
1. 予約を多数登録する
2. 予約一覧が画面下まで伸び、他のUI要素が見えなくなる

## 期待される動作
- 予約一覧部分に最大高さ（例: 400px〜600px程度）を設定し、件数が多い場合は内部でスクロールできるようにする
- 他のUI要素（フォームやヘッダー等）は常に見える状態を維持する

## 実装例（CSSイメージ）
```css
.reservations {
  max-height: 400px;
  overflow-y: auto;
}
```

## 関連ファイル
- index.html
- styles.css
- script.js
